spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: HELLO_SPRING
  profiles:
    redis:
      host: localhost
      port: 6379
    group:
      local: local
      dev: dev
      test: test
  massages:
    basename: i18n/exception
    encoding: UTF-8
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: none

management:
  health:
    elasticsearch:
      enabled: false
app:
  name: helllo
  color: yellow


resilience4j:
  retry:
    instances:
      apiRetry:
        max-attempts: 3       # 최대 재시도 횟수
        wait-duration: 2s     # 재시도 간 대기 시간

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/shop
      username: ldh
      password: doo
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
elasticsearch:
  host: localhost
  port: 9200
  id: elastic
  password: dlengus

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/shop
      username: ldh
      password: doo
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085
elasticsearch:
  host: localhost
  port: 9200
  id: elastic
  password: datalake






